trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'docker-hub perso'
        repository: 'h3rv3/aspnet-docker'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
