trigger:
- main

pool:
  vmImage: ubuntu-latest

- task: Docker@2
  inputs:
    containerRegistry: 'docker-hub perso'
    repository: 'aspnet-docker'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
